apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
type: Opaque
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:pkdA6wVP89s=,iv:Fs625079vA3d1rZsktO+TQYgXeOpQ0JCVUcvcEt2tv0=,tag:1GmwjFSwXgXmqNBMv6sSCw==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:oyujHOPQRieTq5B3Boj0FoTlK/I=,iv:Kkzz7FZ3v7SRTeA4jjKvcAVmsEKc5FROCZGspCS7/5Y=,tag:WtY2E/EJBMneNUW/al2mqg==,type:str]
sops:
    age:
        - recipient: age1f8wxuw4c8v0u25x2fld7ldqmqtw5jkcjm78jltgu050eqyt3sp8s5z5shx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWEczWGpyZ1Y0OWc5UDBR
            enpnN24xTTJ6ZXhvNXdiYXVxb0k5dFhlQldjCktIV2grdDVheC9Ia2Jtb2o3TEUw
            RVEyanRGa1U3Sm1xeVFtUzBTQ0NTbUEKLS0tIExlL1pTZG45dlpDV0JlWG11aHcv
            UWN3dVl3dCtmQmhoWTlsL2I2OUJsOUkKvXIqSztOTsEGlUwZH6Umq2mMmDSLoX6o
            hucoSzQJ/+Z+733m57ozDrM5K2g4QVLKAavEMNdnPwWZBaA/dBkKOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-13T21:54:47Z"
    mac: ENC[AES256_GCM,data:GyTfxmn4N1JOpm42TQWr7mVRb8WndRTbjVeeqBrTXnWKxeAE4FFhW/l2rlPs3tzSsUXsXYVQt85K1VeTymmjnb4pORlZe1c3YNgdk2VHrGAe28JRSe5/V0acElhONkELFZ7di8nH0XO2Hb1bwsgxqghmayHJRodOEj8akdHfk+E=,iv:5NQlquSPnL0hoxe+WKb+qEMow5JOE2DKkOlt3n6OqAo=,tag:gPAW4NDN6xnZhlXP6ONVDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
