apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 66.2.2
            #version: "66.x"
            # version: "58.x"
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
                namespace: monitoring
            interval: 12h
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    driftDetection:
        mode: enabled
        ignore:
            # Ignore "validated" annotation which is not inserted during install
            - paths:
                - /metadata/annotations/prometheus-operator-validated
              target:
                kind: PrometheusRule
    values:
        grafana:
            adminPassword: QFBa!!kmwB2K^b
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.alexsantiago.net
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.alexsantiago.net
sops:
    age:
        - recipient: age1f8wxuw4c8v0u25x2fld7ldqmqtw5jkcjm78jltgu050eqyt3sp8s5z5shx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNHVTOXA1aWxCQVpkUklp
            dGZTZG94T2hZck9pbW1PWlRjVnlBNDVmMzIwCnN1dGdSRnFPNlBNY0VpSExZUVNB
            QVYxOGVJOERMaktYYmxlbHgxaTRMZmcKLS0tIGFXUjlVL3l5TkQ1bVJUM2t4QXZE
            dWszcXFERTVySDJVYlBSM09vS3lTYVkKKy3F1jQmm6KmhRhzEyWvMdiTBISshEOk
            8nhjPCwYnOzndo014CMhZZsGrdzKbiR8TWov/F6fIYHdIniI/awRYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T19:51:13Z"
    mac: ENC[AES256_GCM,data:E7DYvAaTSpInVTudztsniHGogKwhayVUd3fjH/IqhVo+SqTXJ4VC2RnCzCcgHyF3lWlRBJCpdTjrSlZDQi5SMhoC1F3oRgceo6aWb1q8y/vsaj2wbLnhN9I57zqEe19CfC8twoCTZwggY58gfto1CCsLT5CF4msdfSadjoKkuqM=,iv:SfLNqkz+MNtdMP8e+6pgO/E4aF/QZFtao90abfl1XeU=,tag:8QATTAMJ3cBE4FUqQyJFeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
