apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 66.2.2
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
                namespace: monitoring
            interval: 12h
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    driftDetection:
        mode: enabled
        ignore:
            - paths:
                - /metadata/annotations/prometheus-operator-validated
              target:
                kind: PrometheusRule
    values:
        grafana:
            adminPassword: ENC[AES256_GCM,data:GrRdEwCJLK8Ts8npdLI=,iv:gHTeXIrWQn8loeDCaSlg2edgcuXVOFEEwjfEykngf3Y=,tag:+n52stgG7j4BUzpJpsuM+w==,type:str]
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.alexsantiago.net
                tls:
                    - secretName: grafana-tls
                      hosts:
                        - grafana.alexsantiago.net
sops:
    age:
        - recipient: age1f8wxuw4c8v0u25x2fld7ldqmqtw5jkcjm78jltgu050eqyt3sp8s5z5shx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzJQa0pKckZCMWxZaHFr
            RTNZNFVzdEhqeTE5cmFsY2NWYm9iUXYxU0hnCnV1bnJKc2t2a3JNcmFMcjJDYXNW
            TEh6dFBMemhVc0JEQ1NIcFMwVXBxUzAKLS0tIC9IQmljRUxrRlFUSHZvNTMvWXp5
            cEtpeFpLeWxLT2dVL1FpNVNaN1dQRVkKMU0XrkinhSiy4V0THBTQMmfe1ubBKj11
            3cxwCK64K69pH33necUHAnC6hjqs1kkzb9dOz7abdTtw75FLLwebNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-14T20:08:51Z"
    mac: ENC[AES256_GCM,data:I0iTCpM/5R05qcSveGrZEKOgJncVx4sVguUE6SuuABxMAZpivBfUAatjBLg8VEzsFS1uK1BvJxcSU66oFRMrng68UFDfgDMmaJ0J7I2kqLHzJ/sYAGM1MrG20d85MndnaFzToouq2HZBFkdxRcP2srzkdaOAjMAmwUSSQfZoibA=,iv:lwK9lmzB9bylq8uHIda58aa5VSI7UXt4dD5izALTkEE=,tag:+vksDOVnVv0HOYfcJOZdMw==,type:str]
    encrypted_regex: ^(data|stringData|.*password|.*Password)$
    version: 3.10.2
