apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 66.2.2
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
                namespace: monitoring
            interval: 12h
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    driftDetection:
        mode: enabled
        ignore:
            - paths:
                - /metadata/annotations/prometheus-operator-validated
              target:
                kind: PrometheusRule
    values:
        grafana:
            adminPassword: ENC[AES256_GCM,data:HuaAX519BSw7m1ILaIs=,iv:mu1j6mIsI792eATY0sMyqgim7BUGXqELXYEN7zM8DyM=,tag:+nIUA0oKg/i6gmMddLoXlQ==,type:str]
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.alexsantiago.net
<<<<<<< HEAD
=======
                #tls: []
                    - secretName: grafana-tls-secret
                      hosts:
                        - grafana.alexsantiago.net
>>>>>>> 41b948a0834552dca24110c31c045964ec59be14
sops:
    age:
        - recipient: age1f8wxuw4c8v0u25x2fld7ldqmqtw5jkcjm78jltgu050eqyt3sp8s5z5shx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSjJYUndQOUZ5cWs0Q1ps
            bjNtdDhUVTJ1WjhsSVBnSENDSFI4c1JPSmdvCjNieW1JeVd1Q2x0RFBsTitsY0hP
            TmtpRHZVK0oxVURPcXB0bmlCNXBUY0UKLS0tIFFROER5L1lRS2drWURlOGYxc0Ny
            WUV2SkVFb0ZxU0lINkVSbEZPR3BLU0EKkwpl81qfJHmDgjtt9lr4taM1LK7hO220
            BgmVRTGWQ9dANFtUL1EUNPTzZ527WCJ333v+6SoLyeeyC0x2hn0DyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T01:55:32Z"
    mac: ENC[AES256_GCM,data:MA7i/9UzqIfJ6LA+Gf8JUX0piYQKWtJy/UPx9dsko84NVHvcmIRBNxp8SWHpYxOnmYk/frTfoEpby28Lja9Ee8kF2EKsQXLbnckRI8VVK86My/7f3qEA+GmjRXOpGUqDxQtv7TwPMFURqiMk8yFLCxbn87IpKGxDkMI26BIFbDM=,iv:D5Vn6P5dAiTmzWhUeAZC0cwMA51ZxKo3axSQxkoxn7Q=,tag:Q2KfDiPTJi3VtBs7S1v1Ag==,type:str]
    encrypted_regex: ^(.*password|.*Password)$
    version: 3.10.2
