apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kube-prometheus-stack
    namespace: monitoring
spec:
    interval: 30m
    chart:
        spec:
            chart: kube-prometheus-stack
            version: 66.2.2
            sourceRef:
                kind: HelmRepository
                name: kube-prometheus-stack
                namespace: monitoring
            interval: 12h
    install:
        crds: Create
    upgrade:
        crds: CreateReplace
    driftDetection:
        mode: enabled
        ignore:
            - paths:
                - /metadata/annotations/prometheus-operator-validated
              target:
                kind: PrometheusRule
    values:
        grafana:
            adminPassword: ENC[AES256_GCM,data:uLVrIJdokxyCMXd2WF0=,iv:cZwKI/K7HuI2uxAKL1ulMH25itpxA+RSY61+RyOcIN4=,tag:AptNEfRV4HmdB4SiytppJA==,type:str]
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - grafana.alexsantiago.net
sops:
    age:
        - recipient: age1f8wxuw4c8v0u25x2fld7ldqmqtw5jkcjm78jltgu050eqyt3sp8s5z5shx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS3k3cWZ6aDVFVnpwUFRW
            WUtaZHZsczcvODBibUcxWkhuNDh6QjhQU3hVCmlqSVk1ajFxbU5TdlJESWljNzNh
            QXBxSDZacVVPbG1BYmhYZHNVaml6WmMKLS0tIEVpcDlZRDZrZkpidnJOT1RqQ3Jj
            RWl1K3M3YUM0QlB5K1VLY2FyRE9sN2sKD+9edFe8fwgPjVnuIq33cYbRRPydrM2h
            SS2wZL5Yt5FO42ZezP63IiLp0f5hv4EngAce8txxYcI8iXRP/zWKag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-15T02:10:29Z"
    mac: ENC[AES256_GCM,data:groAXxq74kjegzgjgonuvpMMHI1VU9NHhwraSite0B8v0fgdbG33KdzJA4CXAM9DK5d8c6/dAbzyowz0/KNyzRJIbZvYSVeLl3vyYmzxoRqWL3Cr9vJZU98xcXUmUuZoCFCjtsKPQNQ8fSqo0S8HsaovwpyXtzlmO5s0BBwWFY8=,iv:CadIoQupsEVu/EVoyD+4zBE3tmM2oc105MlM2P0E/u4=,tag:qmY/MtToVxyfLJ1OW9it6w==,type:str]
    encrypted_regex: ^(.*password|.*Password)$
    version: 3.10.2
